(() => {
 'use strict';
 const examples=window.VARIMUSE_EXAMPLES,$=id=>document.getElementById(id),picks=new Set();
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let activeView='workspace',detailId=null,branchId=null,branchNumber=0,toastTimer;
 const notes={fatherhood:'The same prompt and a fixed Ideogram V3 Turbo configuration. The recorded style changes from watercolor to illustration.',cabin:'The same cabin brief, with different models and visual settings: Stable Diffusion XL in a sketch direction, and Z-Image Turbo with energetic mood and neon lighting. Several variables change here.',city:'Two published Picks from the same night-market brief, both with Anime and Warm palette settings. The public records do not identify the individual model used for each result.',identity:'Varimuse explored its own identity, too. These are two published Picks from the same logo brief and model-comparison configuration.'};
 function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
 function card(item){return `<article class="image-card"><button class="image-open" data-open="${item.id}" aria-label="Inspect ${esc(item.title)}"><img src="${esc(item.image)}" alt="${esc(item.title)}" loading="lazy" width="1024" height="1024"><span>Inspect result ↗</span></button><div class="card-info"><h3>${esc(item.title)}</h3><p>${esc(item.model||'Original published Pick')}</p><div class="card-actions"><button data-pick="${item.id}" aria-pressed="${picks.has(item.id)}">${picks.has(item.id)?'★ Pick saved':'☆ Keep a Pick'}</button><button data-branch="${item.id}">Branch →</button></div></div></article>`;}
 function render(){const group=$('saved-set').value;$('comparison-grid').innerHTML=examples.filter(x=>x.group===group).map(card).join('');$('full-gallery').innerHTML=examples.map(card).join('');$('picks-gallery').innerHTML=examples.filter(x=>picks.has(x.id)).map(card).join('');$('empty-picks').hidden=picks.size>0;$('pick-count').textContent=picks.size;$('set-note').textContent=notes[group];if(detailId!==null)$('detail-pick').textContent=picks.has(detailId)?'★ Remove demo Pick':'☆ Save a demo Pick';}
 function view(name){activeView=name;['workspace','gallery','picks'].forEach(v=>{$(v+'-view').hidden=v!==name});document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));}
 function plan(){const directions=Number($('direction-count').value),models=[...document.querySelectorAll('[name="model"]:checked')].map(x=>x.value),mode=$('model-mode').value;const count=models.length===0?0:mode==='each'?directions*models.length:directions;$('plan-count').textContent=count+' planned variations';$('plan-detail').textContent=mode==='each'?`${directions} directions × ${models.length} models`:mode==='fixed'?`Fixed: ${models[0]||'choose a model'}`:`${directions} directions across ${models.length} models`;return count;}
 function pick(id){if(picks.has(id))picks.delete(id);else picks.add(id);render();toast(picks.has(id)?'Saved to your demo Picks':'Removed from demo Picks');}
 function inspect(id){const item=examples.find(x=>x.id===id);detailId=id;$('detail-image').src=item.image;$('detail-image').alt=item.title;$('detail-title').textContent=item.title;$('detail-prompt').textContent=item.prompt;const labels={colorPalette:'Palette',aspectRatio:'Aspect ratio'};$('detail-settings').innerHTML=[['Model',item.model||'Not identified in public record'],...Object.entries(item.settings).map(([k,v])=>[labels[k]||k[0].toUpperCase()+k.slice(1),v])].map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');$('detail-date').textContent='Published '+item.date+' · Recovered original artwork and settings';render();$('detail-dialog').showModal();}
 function branch(id){const item=examples.find(x=>x.id===id);branchId=id;if($('detail-dialog').open)$('detail-dialog').close();$('branch-image').src=item.image;$('branch-title').textContent=item.title;$('branch-prompt').value=item.prompt;$('branch-dialog').showModal();}
 document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.dataset.view)view(button.dataset.view);if(button.dataset.open)inspect(Number(button.dataset.open));if(button.dataset.pick)pick(Number(button.dataset.pick));if(button.dataset.branch)branch(Number(button.dataset.branch));});
 $('saved-set').addEventListener('change',render);
 ['model-mode','direction-count','style-mode'].forEach(id=>$(id).addEventListener('change',()=>{if(id==='model-mode'&&$('model-mode').value==='fixed'){[...document.querySelectorAll('[name="model"]:checked')].slice(1).forEach(x=>x.checked=false)}plan();}));
 document.querySelectorAll('[name="model"]').forEach(input=>input.addEventListener('change',()=>{if($('model-mode').value==='fixed'&&input.checked)document.querySelectorAll('[name="model"]').forEach(x=>{if(x!==input)x.checked=false});plan();}));
 $('preview-plan').addEventListener('click',()=>{const count=plan();$('plan-message').textContent=count?`Demo plan prepared: ${count} variations, ${$('style-mode').value==='fixed'?'with one style held fixed':'with styles varied'}. No models were called. Compare the preserved examples below.`:'Select at least one model to prepare a comparison plan.';});
 $('close-detail').addEventListener('click',()=>$('detail-dialog').close());$('close-branch').addEventListener('click',()=>$('branch-dialog').close());$('detail-pick').addEventListener('click',()=>pick(detailId));$('detail-branch').addEventListener('click',()=>branch(detailId));
 $('prepare-branch').addEventListener('click',()=>{const item=examples.find(x=>x.id===branchId);if(!$('branch-prompt').value.trim()){toast('Add a brief for the branch');return;}picks.add(branchId);branchNumber++;$('brief').value=$('branch-prompt').value;$('branch-context').hidden=false;$('branch-context').textContent=`Branch ${branchNumber} prepared from “${item.title}”. The original result and your next brief stay connected in this demo.`;if(branchNumber===1)$('history').innerHTML='<span class="history-start">Original exploration</span>';const arrow=document.createElement('span');arrow.textContent='→';arrow.setAttribute('aria-hidden','true');const node=document.createElement('span');node.className='history-node';node.textContent=`Branch ${branchNumber} · ${item.title}`;$('history').append(arrow,node);$('branch-dialog').close();view('workspace');render();$('branch-context').scrollIntoView({block:'start'});toast('Branch prepared. No new artwork generated.');});
 render();plan();if(location.hash==='#gallery')view('gallery');
})();
